version: "3.9"

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:dev-3.11-bullseye
    volumes:
      - ../.:/workspace
    env_file:
      - .env
    networks:
      - default
    depends_on:
      - db
    command: sleep infinity

  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - 5432:5432



networks:
  default:
    driver: bridge
